name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # External packages (flutter के बाहर)
  file_picker: ^8.0.0
  image_picker: ^1.0.8
  http: ^1.1.0
  dio: ^5.4.0
  just_audio: ^0.9.40
  audio_session: ^0.1.15
  audioplayers: ^5.2.1
  # to read file storage
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5





  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
